### ISSUE TITLE
Add more heart emojis

### ISSUE THREAD

**Issue by kittsville** [mgcoven/Standards#2]
Namely: 
💌
💒
🏩
👨‍❤️‍👨👩‍❤️‍👨👩‍❤️‍👩💏

**Comment by kittsville** [comment]
Missing kissing 😨 
![firefox_2017-11-22_21-23-26](https://user-images.githubusercontent.com/6013087/33150453-689baf4a-cfcb-11e7-93d2-4cb155f2b298.png)

**Comment by haku** [comment]
u1f48f as a png is not in https://github.com/googlei18n/noto-emoji/tree/master/png/128 ... it is the same as emoji_u1f469_200d_2764_200d_1f48b_200d_1f468.png.

**Comment by kittsville** [comment]
Ah, yes. Wondering if to duplicate the image so the emojis line up with their pictures?
