### ISSUE TITLE
Fix emoji description text size

### ISSUE THREAD

**Issue by kittsville** [mgcoven/Standards#6]

**Comment by haku** [comment]
Think I fixed the tabling using a different font size in 3cd810b (forgot to tag the commit).

**Comment by kittsville** [comment]
Moved from a comment on the issue:

>The viewport fix seems to cause more problems than it solves in Firefox for Android. Everything becomes left aligned as the margin: auto stops working. I think mobile display needs some more dedicated work.

(I hadn't noticed you'd commented on this issue >.< )

**Comment by kittsville** [comment]
Applied the temp you mentioned and it seems to work, although we should do some more thorough mobile targeting at some point

**Comment by kittsville** [comment]
I'll close this and open a more general purpose/long term issue for mobile targeting.
